insert into palavra_chave(nome) values('	Animais e acessórios	');
insert into palavra_chave(nome) values('	Esportes	');
insert into palavra_chave(nome) values('	Para a sua casa	');
insert into palavra_chave(nome) values('	Eletrônicos e celulares	');
insert into palavra_chave(nome) values('	Música e hobbies	');
insert into palavra_chave(nome) values('	Bebês e crianças	');
insert into palavra_chave(nome) values('	Moda e beleza	');
insert into palavra_chave(nome) values('	Veículos e barcos	');
insert into palavra_chave(nome) values('	Imóveis	');
insert into palavra_chave(nome) values('	Empregos e negócios	');
insert into palavra_chave(nome) values('	Cachorros e acessórios	');
insert into palavra_chave(nome) values('	Gatos e acessórios	');
insert into palavra_chave(nome) values('	Cavalos e acessórios	');
insert into palavra_chave(nome) values('	Artigos para peixes	');
insert into palavra_chave(nome) values('	Roedores e acessórios	');
insert into palavra_chave(nome) values('	Outros animais e acessórios	');
insert into palavra_chave(nome) values('	Esportes e ginástica	');
insert into palavra_chave(nome) values('	Ciclismo	');
insert into palavra_chave(nome) values('	Fitness e luta	');
insert into palavra_chave(nome) values('	Futebol e acessórios	');
insert into palavra_chave(nome) values('	Pranchas e esp. aquáticos	');
insert into palavra_chave(nome) values('	Skates e patins	');
insert into palavra_chave(nome) values('	Tênis e acessórios	');
insert into palavra_chave(nome) values('	Outros esportes	');
insert into palavra_chave(nome) values('	Móveis	');
insert into palavra_chave(nome) values('	Eletrodomésticos	');
insert into palavra_chave(nome) values('	Jardinagem e construção	');
insert into palavra_chave(nome) values('	Cama, mesa e banho	');
insert into palavra_chave(nome) values('	Arte e decoração	');
insert into palavra_chave(nome) values('	Armários e guarda-roupas	');
insert into palavra_chave(nome) values('	Camas e colchões	');
insert into palavra_chave(nome) values('	Escritório	');
insert into palavra_chave(nome) values('	Estantes	');
insert into palavra_chave(nome) values('	Mesas e cadeiras	');
insert into palavra_chave(nome) values('	Sofás e poltronas	');
insert into palavra_chave(nome) values('	Racks	');
insert into palavra_chave(nome) values('	Videogames	');
insert into palavra_chave(nome) values('	Computadores e acessórios	');
insert into palavra_chave(nome) values('	Celulares e telefonia	');
insert into palavra_chave(nome) values('	Áudio, TV, vídeo e fotografia	');
insert into palavra_chave(nome) values('	Consoles	');
insert into palavra_chave(nome) values('	Jogos	');
insert into palavra_chave(nome) values('	Acessórios	');
insert into palavra_chave(nome) values('	PCs e computadores	');
insert into palavra_chave(nome) values('	Notebook e netbook	');
insert into palavra_chave(nome) values('	Ipad e tablet	');
insert into palavra_chave(nome) values('	Impressoras e suplementos	');
insert into palavra_chave(nome) values('	Peças e acessórios	');
insert into palavra_chave(nome) values('	iPhone Apple	');
insert into palavra_chave(nome) values('	Nextel	');
insert into palavra_chave(nome) values('	Samsung	');
insert into palavra_chave(nome) values('	LG	');
insert into palavra_chave(nome) values('	Nokia	');
insert into palavra_chave(nome) values('	Motorola	');
insert into palavra_chave(nome) values('	Sony Ericsson	');
insert into palavra_chave(nome) values('	Blackberry	');
insert into palavra_chave(nome) values('	HTC	');
insert into palavra_chave(nome) values('	Outras marcas	');
insert into palavra_chave(nome) values('	Telefones	');
insert into palavra_chave(nome) values('	Instrumentos musicais	');
insert into palavra_chave(nome) values('	Música e filmes (DVDs, etc.)	');
insert into palavra_chave(nome) values('	Livros e revistas	');
insert into palavra_chave(nome) values('	Antiguidades	');
insert into palavra_chave(nome) values('	Hobbies e coleções	');
insert into palavra_chave(nome) values('	Guitarras	');
insert into palavra_chave(nome) values('	Violões	');
insert into palavra_chave(nome) values('	Baixos	');
insert into palavra_chave(nome) values('	Cavaquinhos	');
insert into palavra_chave(nome) values('	Baterias e pratos	');
insert into palavra_chave(nome) values('	Teclados e pianos	');
insert into palavra_chave(nome) values('	Violinos e violoncellos	');
insert into palavra_chave(nome) values('	Instrumentos de sopro	');
insert into palavra_chave(nome) values('	Amplificadores e microfones	');
insert into palavra_chave(nome) values('	Outros instrumentos	');
insert into palavra_chave(nome) values('	Roupas	');
insert into palavra_chave(nome) values('	Brinquedos	');
insert into palavra_chave(nome) values('	Carrinhos e cadeirinhas	');
insert into palavra_chave(nome) values('	Berço e móveis	');
insert into palavra_chave(nome) values('	Beleza e saúde	');
insert into palavra_chave(nome) values('	Roupas e calçados	');
insert into palavra_chave(nome) values('	Bolsas, malas e mochilas	');
insert into palavra_chave(nome) values('	Bijouterias, relógios e acessórios	');
insert into palavra_chave(nome) values('	Calçados	');
insert into palavra_chave(nome) values('	Vestidos e Saias	');
insert into palavra_chave(nome) values('	Casacos e Jaquetas	');
insert into palavra_chave(nome) values('	Camisas e Camisetas	');
insert into palavra_chave(nome) values('	Calças	');
insert into palavra_chave(nome) values('	Shorts e Bermudas	');
insert into palavra_chave(nome) values('	Carros	');
insert into palavra_chave(nome) values('	Caminhões, ônibus e vans	');
insert into palavra_chave(nome) values('	Motos	');
insert into palavra_chave(nome) values('	Barcos, lanchas e aviões	');
insert into palavra_chave(nome) values('	Apartamentos	');
insert into palavra_chave(nome) values('	Casas	');
insert into palavra_chave(nome) values('	Aluguel de quartos	');
insert into palavra_chave(nome) values('	Temporada	');
insert into palavra_chave(nome) values('	Terrenos, sítios e fazendas	');
insert into palavra_chave(nome) values('	Lojas, salas e outros	');
insert into palavra_chave(nome) values('	Lançamentos	');
insert into palavra_chave(nome) values('	Cobertura	');
insert into palavra_chave(nome) values('	Duplex/Triplex	');
insert into palavra_chave(nome) values('	Kitchenette	');
insert into palavra_chave(nome) values('	Loft/Studio	');
insert into palavra_chave(nome) values('	Rua pública	');
insert into palavra_chave(nome) values('	Vila	');
insert into palavra_chave(nome) values('	Condomínio fechado	');
insert into palavra_chave(nome) values('	Apartamento	');
insert into palavra_chave(nome) values('	Casa	');
insert into palavra_chave(nome) values('	Quarto	');
insert into palavra_chave(nome) values('	Quarto Compartilhado	');
insert into palavra_chave(nome) values('	Pousada	');
insert into palavra_chave(nome) values('	Terrenos e lotes	');
insert into palavra_chave(nome) values('	Sítios e chácaras	');
insert into palavra_chave(nome) values('	Fazendas	');
insert into palavra_chave(nome) values('	Lojas e salas comerciais	');
insert into palavra_chave(nome) values('	Terrenos e loteamentos	');
insert into palavra_chave(nome) values('	Ofertas de emprego	');
insert into palavra_chave(nome) values('	Currículos	');
insert into palavra_chave(nome) values('	Serviços	');
insert into palavra_chave(nome) values('	Indústria, comércio e agro	');

